### ISSUE TITLE
Remove bundled pyqtgraph?

### ISSUE THREAD

**Issue by ojdf** [AOtools/soapy#128]
The old version of pyqtgraph bundled with soapy is causing some problems, such as #121. I've encountered some other issues with python 3.10+ too. Should we remove the pyqtgraph bundled with soapy and add as a dependancy? I can't remember the reason for bundling it in the first place. Pyqtgraph is installable via pip and conda now which may not have been the case when originally developing the GUI. 

If we don't remove it, it at least needs an update.

**Comment by andrewpaulreeves** [comment]
Yes, lets just add it as a requirement...
