### ISSUE TITLE
Error on importing Soapy (module not found libmmd.dll) 

### ISSUE THREAD

**Issue by TomP4211** [AOtools/soapy#140]
Here is the error description that is printed when i try to import soapy. 

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Untitled-1.ipynb Cell 2 in <cell line: [1](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#W1sdW50aXRsZWQ%3D?line=0)>()
----> 1 import soapy

File ~\AppData\Roaming\Python\Python310\site-packages\soapy\__init__.py:35, in <module>
     32 # Load the DLL manually to ensure its handler gets
     33 # set before our handler.
     34 basepath = os.path.dirname(sys.executable)
---> 35 ctypes.CDLL(os.path.join(basepath, "Library", "bin", 'libmmd.dll'))
     36 ctypes.CDLL(os.path.join(basepath, "Library", "bin", 'libifcoremd.dll'))
     38 # Now set our handler for CTRL_C_EVENT. Other control event
     39 # types will chain to the next handler.

File c:\Program Files\Python310\lib\ctypes\__init__.py:374, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    371 self._FuncPtr = _FuncPtr
    373 if handle is None:
--> 374     self._handle = _dlopen(self._name, mode)
    375 else:
    376     self._handle = handle

FileNotFoundError: Could not find module 'c:\Program Files\Python310\Library\bin\libmmd.dll' (or one of its dependencies). Try using the full path with constructor syntax.
---------------------------------------------------------------------------------------------------------------------

That directory \Library\bin\ does not exist in my python installation, nor the .dll files.
I installed soapy using python setup.py install.

**Comment by CJones-Optics** [comment]
You will need to go and comment out the entire if `sys.platform == "win32"` block in the `__init__.py` (Lines 23-46) "...\.venv\Lib\site-packages\soapy\__init__.py" It doesn't seem to work as expected. 

I think it is a bodge around an issue that doesn't exist on windows anymore. A ctrl-c event might crash the interpreter if you do this, but better than it not working. 

 I'll make a pull request if I get round to making sure there aren't any other side effects.

**Comment by matthewtownson** [comment]
I have had a similar issue, and also found that removing the old code which checks for "win32" fixes the issue. Thanks for volunteering to make the changes and do a pull request @CJones-Optics

**Comment by CJones-Optics** [comment]
> I have had a similar issue, and also found that removing the old code which checks for "win32" fixes the issue. Thanks for volunteering to make the changes and do a pull request @CJones-Optics

I was just about to do the pull request and saw that you had already made the pull request back in Jan, but not accepted it yet Haha. https://github.com/AOtools/soapy/pull/138

**Comment by ojdf** [comment]
Thanks @CJones-Optics for reminding us that @matthewtownson had already fixed the problem!

I've merged his PR #138 so this should be fixed now.
