### ISSUE TITLE
Migrate to using 'aotools' repository

### ISSUE THREAD

**Issue by andrewpaulreeves** [AOtools/soapy#59]
AOTools aims to be a nice collection of Python tools for AO that should be re-used by Soapy rather than the slightly odd 'aoSimLib.py' library. There are a couple of options to integrate it, either 
- copying across a snapshot of the aotools libraries
- setting up a git "submodule"

Not sure which to go with

**Comment by matthewtownson** [comment]
I think it ought to be a submodule. The tools are useful outside of soapy, and could be developed separately,  so to me it makes sense that it is its own repository, with soapy requiring it.

**Comment by matthewtownson** [comment]
Now we have soapy and aotools separated, what do we want to do about the dependency? Do we just want to have aotools as a dependency, so can close this, or do we want to use submodules?

**Comment by andrewpaulreeves** [comment]
Great point - this should have been closed literally *years* ago! Its a dependency obv!
