### ISSUE TITLE
Problem with saveLgsPsf: True

### ISSUE THREAD

**Issue by stefanocovino** [AOtools/soapy#72]
Hello,

I am following the on-line tutorial creating a SCAO conf file to simulate the CANARY instrument and, possibly, I found a bug.

If I set in the conf file 

saveLgsPsf: False

everything seems to work fine. On the other hand setting the entry to "True" I get these messages and an error:

soapy conf/CANARY_SCAO.yaml
Pixel Scale: 30.48 pxls/m
subScreenSize: 154 simulation pixels
1 of 1: Loaded configuration file successfully!
Starting Sim: 2017-04-18-16-07-56
Pixel Scale: 30.48 pxls/m
subScreenSize: 154 simulation pixels
Creating mask...
Turbulence summary @ 500 nm:
| r0 = 0.14 m (0.74" seeing)
| Vbar_5/3 = 11.90 m/s
| tau0 = 3.69 ms
Generating Phase Screens
Generate Phase Screen 0  with r0: 0.24, size: 2048
Generate Phase Screen 1  with r0: 0.32, size: 2048
Generate Phase Screen 2  with r0: 0.41, size: 2048
Generate Phase Screen 3  with r0: 0.62, size: 2048
Generate Phase Screen 4  with r0: 0.62, size: 2048
Initialising WFSs....
AOFFT.py -> __init__: No pyfftw available.                                 Defaulting to scipy.fftpack
WFS 0: 72 measurements
Initialising 2 DMs...
DM 0: 2 active actuators
DM 1: 60 active actuators
62 total DM Actuators
Initialising Reconstructor...
Initialising 1 Science Cams...
AOFFT.py -> __init__: No pyfftw available.                                 Defaulting to scipy.fftpack
Initialise Data Storage...
Traceback (most recent call last):
  File "/Users/covino/owncloud/Pacchetti/anaconda3/bin/soapy", line 4, in <module>
    __import__('pkg_resources').run_script('soapy==0.13.1', 'soapy')
  File "/Users/covino/owncloud/Pacchetti/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/covino/owncloud/Pacchetti/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/Users/covino/owncloud/Pacchetti/anaconda3/lib/python3.5/site-packages/soapy-0.13.1-py3.5.egg/EGG-INFO/scripts/soapy", line 92, in <module>
    runCmdSim(sim, interactive=args.interactive)
  File "/Users/covino/owncloud/Pacchetti/anaconda3/lib/python3.5/site-packages/soapy-0.13.1-py3.5.egg/EGG-INFO/scripts/soapy", line 35, in runCmdSim
    sim.aoinit()
  File "/Users/covino/owncloud/Pacchetti/anaconda3/lib/python3.5/site-packages/soapy-0.13.1-py3.5.egg/soapy/simulation.py", line 264, in aoinit
    self.initSaveData()
  File "/Users/covino/owncloud/Pacchetti/anaconda3/lib/python3.5/site-packages/soapy-0.13.1-py3.5.egg/soapy/simulation.py", line 650, in initSaveData
    if self.config.wfss[lgs].lgsUplink:
AttributeError: 'WfsConfig' object has no attribute 'lgsUplink'

Thanks a lot for your attention, and I hope not to bore you too much.
   Stefano

**Comment by andrewpaulreeves** [comment]
Hi again Stefano,

Apologies that you've been running into a few bugs! I've fixed LGS PSF saving again now in PR #73 . It might be best if you just use the master branch rather than me drafting a new release in case you find anything else that needs fixing. You're certainly not boring me - I really appreciate your help in finding and reporting these bugs!

Cheers,

Andrew

**Comment by stefanocovino** [comment]
> 
> Hi again Stefano,
> 
> Apologies that you've been running into a few bugs! I've fixed LGS PSF saving again now in PR #73 <https://github.com/AOtools/soapy/pull/73> . It might be best if you just use the master branch rather than me drafting a new release in case you find anything else that needs fixing. You're certainly not boring me - I really appreciate your help in finding and reporting these bugs!
> 
> Cheers,
> 
> Andrew
> 
> 

Hello Andrew,

sorry for that, I have not realised that I was using the wrong branch.


I report here a couple of very minor things about the documentation I am browsing these days. 

In the section devoted to the CANARY SCAO I guess that in the box with the python commands sim.aoinit() should go before sim.makeIMat().
And later the two imshow commands should be read pyplot.imshow.

And, again, thanks for having provided this excellent simulator.


Bye,
	Stefano
